site_name: My Docs
theme:
  name: material
  language: ja
  font: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
    - codehilite:
        noclasses: true
        pygments_style: colorful
        linenums: true
    - admonition
    - pymdownx.superfences
